// Generated by CoffeeScript 1.7.1
(function() {
  var concerne_html, init;

  init = function(id) {
    var html;
    $('#' + id).prop('checked', true);
    $('#form_concerne').empty();
    html = concerne_html(id);
    return $('#form_concerne').append(html);
  };

  concerne_html = function(id) {
    var html;
    switch (id) {
      case 'type_form_infos':
        html = "<select> <option value='web'>Création de sites web</option> <option value='gestion'>Création de logiciels de gestion</option> <option value='hebergement'>L'hébergement</option> <option value='Autre'>Autres</option> </select>";
        break;
      case 'type_form_devis':
        html = "<select> <option value='web'>Devis de sites web</option> <option value='gestion'>Devis de logiciels de gestion</option> <option value='hebergement'>Devis hébergement</option> <option value='Autre'>Autres</option> </select>";
        break;
      case 'type_form_suivit':
        html = "<select> <option value='web'>Avancement du projet ?</option> <option value='gestion'>Demande de modifications</option> <option value='hebergement'>Envoi d'informations ( texte, images, ... )</option> <option value='Autre'>Autres</option> </select>";
    }
    return html;
  };

  jQuery(function() {

    /* your code here */
    var id, _i, _len, _ref;
    init('type_form_infos');
    _ref = ['type_form_infos', 'type_form_devis', 'type_form_suivit'];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      id = _ref[_i];
      $('#' + id).click(function() {
        init(this.id);
      });
    }
  });

}).call(this);
